language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - CODECLIMATE_REPO_TOKEN=4cb213e0d2f100ea9ca805419421219972940aeaee82f7326f1fcf6608e788e0 ./vendor/bin/test-reporter
