name: PHP

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    strategy:
      max-parallel: 15
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php-version }} Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
      
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.37.1
      with:
        php-version: ${{ matrix.php-version }}
        coverage: pcov
    
    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test:coverage

    - uses: actions/upload-artifact@v6
      if: matrix.php-version == '8.4'
      with:
        name: reports-${{ matrix.os }}-${{ matrix.php-version }}
        retention-days: 1
        path: |
          **/coverage.xml
          **/test-report.xml
          !node_modules/**

  laravel:
    strategy:
      max-parallel: 15
      matrix: 
        include:
          # Laravel 12
          - php: 8.4
            phpunit: 13
            testbench: 10
          # Laravel 13
          - php: 8.3
            phpunit: 12
            testbench: 11

    name: "PHP: ${{ matrix.php }} Testbench: ${{ matrix.testbench }} PHPUnit ${{ matrix.phpunit }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
      
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.37.1
      with:
        php-version: ${{ matrix.php }}

    - name: Install dependencies
      run: composer require --dev phpunit/phpunit:^${{ matrix.phpunit }} orchestra/testbench:^${{ matrix.testbench }}

    - name: Run test suite
      run: composer run-script test
