name: PHP

on: ['push']

jobs:
  build:
    strategy:
      max-parallel: 15
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    
    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

  laravel:
    strategy:
      max-parallel: 15
      matrix: 
        include:
          - php: 8.1
            phpunit: 8
            testbench: 6
          - php: 8.1
            phpunit: 9
            testbench: 7
          - php: 8.1
            phpunit: 9
            testbench: 8
          - php: 8.3
            phpunit: 10
            testbench: 9

    name: "PHP: ${{ matrix.php }} Testbench: ${{ matrix.testbench }} PHPUnit ${{ matrix.phpunit }}"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Install dependencies
      #run: composer install --prefer-dist --no-progress
      run: composer require --dev phpunit/phpunit:^${{ matrix.phpunit }} orchestra/testbench:^${{ matrix.testbench }}

    - name: Run test suite
      run: composer run-script test


  #sonarcloud:
  #  runs-on: ubuntu-latest
  #  if: github.event_name != 'pull_request'

  #  name: "SonarCloud"
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: Setup PHP
  #    uses: shivammathur/setup-php@master
  #    with:
  #      php-version: 7.4
  #      coverage: pcov

    #- name: Install dependencies
    #  run: composer install --prefer-dist --no-progress

    #- name: Run test suite
    #  run: composer run-script test -- --coverage-clover=coverage.clover --log-junit=test-report.xml

      # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747/5
    #- name: fix code coverage paths
    #  run: sed -i 's/\/home\/runner\/work\/Core\/Core\//\/github\/workspace\//g' coverage.clover
      
    #- name: SonarCloud Scan
    #  uses: SonarSource/sonarcloud-github-action@v1.1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}